### ISSUE TITLE
at.chromaticity does not work with recent 6d modifications

### ISSUE THREAD

**Issue by lcarver** [atcollab/at#528] opened 2022-11-30 08:39 UTC

**Comment by swhite2401** [comment] 2022-12-08 22:41
I have looked at it a bit, in the past this function was decorated with `check_radiation(False)` so it was not available for 6d lattices.
Now the decorator was remove but an error is raised instead because it requires to compute the tune for several `dp` offset.

This error was introduced in #505 even thought I thought we had agreed that no error shall be issued in `find_orbit6` but rather leaving the warning saying that `dp` and `dct` inputs would be ignored. A change of strategy is fine for me but may have consequence for codes using `find_orbit()` and trying to handle 6d and 4d cases... this was already discussed at length in fact.

A decorator exist this shift the frequency of a 6d lattice based on `dp` argument `revolution.frequency_control(func)`. We could use it in `at.chromaticity` but I think the problem is more general.

Due to the ordering of import we cannot use it in `orbit.py` or `matrix.py` however we may import it in `linear.py` to decorate `linopt6`, `get_tune` and `get_chrom` and allow for 6d calculations with `dp `offsets -> is there a reason why this was not done before?

More difficult: can we build a similar decorator in `orbit.py` to solve the problem at the source? (for df input this is rather trivial)
I am sorry to revive again this question but this is really not a nice feature for the user that one of the most basic at function keeps throwing errors all the time....

**Comment by swhite2401** [comment] 2023-02-23 15:23
Fixed in #540

**Closed by swhite2401** 2023-02-23 15:23 UTC
Labels: Python
